### PR TITLE
Mobile - Fix overflowing blog post title

### LINKED ISSUE #301: Mobile - Long blog posts titles overflow on mobile devices
Split from #247 

**Plan**
- [ ] check current `font-size` of a blog post title
- [ ] try out different `font-size` values 
- [ ] try `word-break` property
- [ ] try hyphenation

**Options**

1.  Keep current size - xlarge or 3.5rem or 63px and `word-break`
blog_title_word-break_xlarge_font_size

2. Smaller but still large font size (36px) and `word-break`
36px

or on a smaller device
36px-smaller-device

3. Medium font size - `word-break` would be useless here as `font-size` value is small enough to fit the title on the screen
a) example with medium font-size (22.5px or 1.25rem) and `word-break` property on
blog_post_title_medium_font_size_word-break

b)example with medium font-size (22.5px or 1.25rem) and `word-break` property _**off**_
blog_post_title_medium_font_size_no_word-break

### PR DESCRIPTION
**Pull request by AlinChindea**
Fixes #301 

## Description

- adds a `word-break` property for longer words
- adds css hyphenation for supported browsers 
- decreases blog post title font-size form xlarge (63px) to large (36px) for all device sizes

### CODE REVIEW

File: src/components/Text.js [hunk 1]
```diff
@@ -24,6 +24,11 @@ const Text = ({
   lineHeight = 1.5,
   underline,
   display = 'inline-block',
+  wordBreak = 'normal',
+  overflowWrap = 'normal',
+  WebkitHyphens = 'none',
+  msHyphens = 'none',
+  hyphens = 'none',
```
Comment (RpprRoger) [inline src/components/Text.js]: I think we should have fewer props, can we simplify this? We could start with leaving the vendor prefix version complications at this level, and providing a simpler API to the consumers of `Text`

**Comment by RpprRoger** [comment]
Worked with @AlinChindea on a call to refactor some of it. Looks like it's working OK on my note8
